package datasource;

import domain.AudioCodec;
import domain.Product;
import domain.VideoStreaming;

import java.sql.*;
import java.util.*;
import java.util.function.Function;

public class ProductGateway {

    private long id;
    private ProductType type;
    private String sku;
    private String name;
    private double basePrice;
    private Long size = null;
    private Boolean hasLyrics = null;
    private Set<AudioCodec> codecs = null;
    private boolean hasSubtitles;
    private int videoResolution;
    private ArrayList<VideoStreaming> supportedStreamingServices;

    /**
     * Create constructor - used to put a new object into the db
     *
     * @param type
     * @param sku
     * @param name
     * @param basePrice
     * @param size
     * @param hasLyrics
     * @param codecs
     * @param supportedStreamingServices
     */
    public ProductGateway(ProductType type, String sku, String name, double basePrice, long size, Boolean hasLyrics, Set<AudioCodec> codecs, ArrayList<VideoStreaming> supportedStreamingServices) throws DatabaseException {
        this.type = type;
        this.sku = sku;
        this.name = name;
        this.basePrice = basePrice;
        this.size = size;
        this.hasLyrics = hasLyrics;
        this.codecs = codecs;
        this.supportedStreamingServices = supportedStreamingServices;


        insertNewRow();
        //this.id = getId();
        // TODO set the id with the one generated by the INSERT
        // TODO now you have to store the many to many relationship
    }


    /**
     * A finder constructor that will be used by findAndBuild only
     *
     * @param id
     */
    private ProductGateway(long id) throws DatabaseException {
        String sql = "Select * FROM products Where id = ?";

        Connection conn = getConnection();
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setLong(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                getDataOutOfResultSet(rs);
            }
        } catch (SQLException e) {
            throw new DatabaseException(e.getMessage());
        }
    }

    private ProductGateway() {
        // Used to have empty gateways that we fill in incrementally
    }

    static void createTable() throws DatabaseException {

        String sql = "CREATE TABLE IF NOT EXISTS products (" + " id INTEGER PRIMARY KEY AUTOINCREMENT," + " sku TEXT," + " name TEXT," + " basePrice DOUBLE," + " size INTEGER," + " hasLyrics BOOLEAN," + " codecs INTEGER" + ");";

        // Establish connection and execute statement
        Connection conn = getConnection();
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        } catch (SQLException e) {
            throw new DatabaseException(e.getMessage());
        }
    }

     public static List<Product> findAllRows(Map<ProductType, Function<ProductGateway, ? extends Product>> builders) throws DatabaseException {
        List<Product> products = new ArrayList<>();

        // find and build them all here

        return products;
    }

    public static <T> T findAndBuild(long id, Function<ProductGateway, T> domainBuilder) throws DatabaseException {
        ProductGateway gateway = new ProductGateway(id);
        return domainBuilder.apply(gateway);
    }

    private static Connection getConnection() throws DatabaseException {
        Connection conn = null;
        try {
            conn = DatabaseRegistry.getConnection();
        } catch (SQLException e) {
            throw new DatabaseException(e.getMessage());
        }
        return conn;
    }

    private void getDataOutOfResultSet(ResultSet rs) throws SQLException {
        this.id = rs.getLong("id");
        this.sku = rs.getString("sku");
        this.name = rs.getString("name");
        this.basePrice = rs.getDouble("basePrice");
        this.size = rs.getLong("size");
        this.hasLyrics = rs.getBoolean("hasLyrics");
        this.codecs = getSupportedCodecsSet(rs.getInt("codecs"));
    }

    int calculateBitmask(Set<AudioCodec> codecs) {
        if (codecs == null) return 0;

        int mask = 0;
        for (AudioCodec codec : codecs) {
            // Shift 1 left by the enum's ordinal position to create the binary flag
            mask |= (1 << codec.ordinal());
        }
        return mask;
    }

    public double getBasePrice() {
        return basePrice;
    }

    public Set<AudioCodec> getCodecs() {
        return codecs;
    }

     public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public long getSize() {
        return size;
    }

    public String getSku() {
        return sku;
    }

    private Set<AudioCodec> getSupportedCodecsSet(int mask) {
        Set<AudioCodec> codecs = new java.util.HashSet<>();

        AudioCodec[] values = AudioCodec.values();
        for (int i = 0; i < values.length; i++) {
            // Check if the i-th bit is set to 1
            if ((mask & (1 << i)) != 0) {
                codecs.add(values[i]);
            }
        }
        return codecs;
    }

    public ArrayList<VideoStreaming> getSupportedStreamingServices() {
        return supportedStreamingServices;
    }

    public ProductType getType() {
        return type;
    }

    public int getVideoResolution() {
        return videoResolution;
    }

    private void insertNewRow() throws DatabaseException {
        String sql = "INSERT INTO products (sku, name, basePrice, size, hasLyrics, codecs) " +
                "VALUES (?, ?, ?, ?, ?, ?);";

        Connection conn = getConnection();
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, sku);
            pstmt.setString(2, name);
            pstmt.setDouble(3, basePrice);
            if(size != null) {
                pstmt.setLong(4, size);
            }
            else{
                pstmt.setNull(4, Types.NULL);
            }
            if(hasLyrics != null) {
                pstmt.setBoolean(5, hasLyrics);
            }
            else {
                pstmt.setNull(5, Types.NULL);
            }
            if(codecs != null) {
                pstmt.setInt(6, calculateBitmask(codecs));
            }
            else {
                pstmt.setNull(6, Types.NULL);
            }

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        this.id = generatedKeys.getLong(1);
                    }
                }
            }
            assert !conn.isClosed();
        } catch (SQLException e) {
            throw new DatabaseException(e.getMessage());
        }
    }

    public boolean isHasLyrics() {
        return hasLyrics;
    }

    public boolean isHasSubtitles() {
        return hasSubtitles;
    }
}
