package datasource;

import domain.AudioCodec;
import domain.Cost;
import domain.VideoStreaming;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.function.Function;

public class ProductGateway {

    private long id;
    private ProductType type;
    private String sku;
    private String name;
    private double basePrice;
    private long size;
    private boolean hasLyrics;
    private Set<AudioCodec> codecs;
    private boolean hasSubtitles;
    private int videoResolution;
    private ArrayList<VideoStreaming> supportedStreamingServices;

    //========================================================================================================
    // This is where the table driven gateway's static methods should go
    //========================================================================================================
    public static List<ProductGateway> findAllRows() {
        return null;
    }


    public long getId() {
        return id;
    }

    public ProductType getType() {
        return type;
    }

    public String getSku() {
        return sku;
    }

    public String getName() {
        return name;
    }

    public double getBasePrice() {
        return basePrice;
    }

    public long getSize() {
        return size;
    }

    public boolean isHasLyrics() {
        return hasLyrics;
    }

    public Set<AudioCodec> getCodecs() {
        return codecs;
    }

    public boolean isHasSubtitles() {
        return hasSubtitles;
    }

    public int getVideoResolution() {
        return videoResolution;
    }

    public ArrayList<VideoStreaming> getSupportedStreamingServices() {
        return supportedStreamingServices;
    }

    /**
     * Create constructor - used to put a new object into the db
     * @param type
     * @param sku
     * @param name
     * @param basePrice
     * @param size
     * @param hasLyrics
     * @param codecs
     * @param supportedStreamingServices
     */
    public ProductGateway(ProductType type, String sku, String name, double basePrice,
                          long size, boolean hasLyrics, Set<AudioCodec> codecs, ArrayList<VideoStreaming> supportedStreamingServices) {
        this.type = type;
        this.sku = sku;
        this.name = name;
        this.basePrice = basePrice;
        this.size = size;
        this.hasLyrics = hasLyrics;
        this.codecs = codecs;
        this.supportedStreamingServices = supportedStreamingServices;


        // TODO use INSERT to put this row into the table
        // TODO set the id with the one generated by the INSERT
        // TODO now you have to store the many to many relationship
    }

    /**
     * A finder constructor that will be used by findAndBuild only
     * @param id
     */
    private ProductGateway(long id) {
        // TODO build the right select statement
        // TODO fill all of the instance variables from that select statement
    }

    public static <T> T findAndBuild(long id, Function<ProductGateway, T> domainBuilder) {
        ProductGateway gateway = new ProductGateway(id);

        // TODO call the domainBuilder to get the object and return it
        return null;
    }

    private Set<AudioCodec> getSupportedCodecsSet(int mask) {
        Set<AudioCodec> codecs = new java.util.HashSet<>();
        // TODO set the codecs from the mask
        // Yes, you will need to see the enum that is in the domain layer. The domain is really the center of the
        // world and exposing read only values isn't really terrible

        return codecs;
    }

    private int calculateBitmask(Set<AudioCodec> codecs) {
        // TODO convert the codes to a bit mask
        return 0;
    }
}
